fieldLayouts:
  ad8c3559-8cce-4e9e-85c3-90b119c45024:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 902e63b8-43e3-4fa4-9ed8-41e68deaa2ec
            warning: null
            width: 100
          -
            fieldUid: 60f68e37-4450-4637-9aa6-cd762c626e09 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3343844-f7cb-49bf-8950-94750766bfef
            warning: null
            width: 100
          -
            fieldUid: 4573f8e8-4efd-43b6-a0dc-bcbd389b998a # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcdec8df-20c2-450f-8912-1c3154d554e3
            warning: null
            width: 100
          -
            fieldUid: d5e2b9c0-5808-45a6-bee4-aacb1a2c3155 # Page Copy
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91bf3f2b-9ccc-46af-ac72-0fee4726a525
            warning: null
            width: 100
        name: Content
        uid: 8a080f7a-c738-4c34-a70d-f404a9a1667f
handle: aboutCraftyCoffee
hasTitleField: true
name: 'About Crafty Coffee'
section: 4734c74d-7cf0-4303-8ee0-121dafa7481a # About Crafty Coffee
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
