fieldLayouts:
  b4bbbf2b-8fe6-4978-8956-9a73c007a9d5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: 'enter a drink name'
            label: 'Drink Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05eba697-5cdb-41a9-bbef-51f14b5b729d
            warning: null
            width: 100
          -
            fieldUid: 2c2d8dee-ad22-4ab5-bebd-1659537be168 # Drink Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e5fda5-5a5e-4a22-86bd-14513d23cb7a
            warning: null
            width: 100
          -
            fieldUid: cfe82d92-4cbb-4e92-b4bf-5ffa5b41c446 # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f570ad4c-63b3-41e6-8215-f138922265d2
            warning: null
            width: 100
          -
            fieldUid: d5e2b9c0-5808-45a6-bee4-aacb1a2c3155 # Page Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ae2d3b7-2bf3-4666-902a-a024545f3375
            warning: null
            width: 100
          -
            fieldUid: 2dc8e307-8525-4259-978f-8d850f7072e8 # Drink image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14b446f4-1ca4-4733-b41c-203dceb7a027
            warning: null
            width: 100
          -
            fieldUid: f57baedc-d9b7-44a2-aea7-c1c503a66c5f # Drink Recipe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7b62879-8f0c-47d2-83da-380bbfbb1a6f
            warning: null
            width: 100
        name: Content
        uid: 33f89bfb-c039-42a0-84ac-617582275f25
handle: drink
hasTitleField: true
name: Drink
section: 2dc95fd7-9d33-489d-97ed-677f71655898 # Drinks
sortOrder: 1
titleFormat: 'Drink Name'
titleTranslationKeyFormat: null
titleTranslationMethod: site
