fieldLayouts:
  f507a11c-64fd-4d73-b534-8733005a62c1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e85e7f0-cceb-470d-9c14-fdff1f6e23fe
            warning: null
            width: 100
          -
            fieldUid: e0facf09-85d5-48e9-a9f0-7dea8495e212 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd46e23-56f8-4888-bbc4-98c1708637e1
            warning: null
            width: 100
          -
            fieldUid: 2464c8e3-47b7-46b4-8ea4-38aa941ce23e # News Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 416e6082-8c43-4755-8c52-77f13d8f92ef
            warning: null
            width: 100
        name: Content
        uid: 8755e88e-feb2-4c73-a682-c010412f7520
handle: news
hasTitleField: true
name: News
section: 9f84328c-d83b-4a61-acdf-b1a9f26dfce6 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
