defaultPlacement: end
fieldLayouts:
  275d6b7f-7ffa-46e5-be82-c9f753dae713:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: cfd684df-f3f1-4289-8fb2-8bf0d3f25ab9
            warning: null
            width: 100
          -
            fieldUid: 331217c2-5b7f-47f0-aefa-f8ac7df76ce9 # Styles Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cb3a2ec-04c2-499f-8436-962ac7fb74ee
            warning: null
            width: 100
        name: Content
        uid: 79754dc7-2a52-4059-9176-46386a1b24c6
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  a2df9887-05e2-432f-a020-eb58a337372f: # blog.test
    hasUrls: true
    template: styles/_entry
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: 5
  uid: 9f670301-5289-48f6-b2c2-65f5f5a9b142
