defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2df9887-05e2-432f-a020-eb58a337372f: # blog.test
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
